"""empty message

Revision ID: ee72ed354eda
Revises: 
Create Date: 2022-07-16 00:34:55.061668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee72ed354eda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'urls', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'visits', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'urls', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    # ### end Alembic commands ###
